version: '3.8'

services:
  app:
    build: .
    ports:
      - "3000:3000"
    env_file:
      - .env.development
    depends_on:
      - db
      - pgadmin
    volumes:
      - .:/app  # Esto asegura que todos los archivos locales se copien en tiempo de ejecución.
      - /app/node_modules  # Evitar conflicto de node_modules con la máquina host

  db:
    image: postgres:latest
    env_file:
      - .env.development
    ports:
      - "5432:5432"
    volumes:
      - db-data:/var/lib/postgresql/data

  pgadmin:
    image: dpage/pgadmin4
    ports:
      - "5050:80"
    env_file:
      - .env.development

volumes:
  db-data: 